version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=reunion
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_LOCAL_INFILE=1  # Permite cargar archivos locales usando LOAD DATA INFILE
    command: --ssl=0  # Deshabilita el uso de SSL
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
